Merge pull request #5 from amir-raissi/add_erc20_token
amir-raissi/crypto-slots pull request #6
Opened 2022-04-12 19:20 UTC by jake-ritz11

2022-04-12 19:30 UTC, ahantke1 submitted a review, later dismissed
Looks like a good start to me! Only need to add the actual spin logic (however many functions that may be) now.

2022-04-12 20:10 UTC, amir-raissi commented
Looks good to me besides that one comment which may or may not be an issue. 

As for the amount of ETH to charge per token I think it should be in relation to the jackpot or we could totally just set it statically at like .00X eth. Something to think about for sure tho

2022-04-12 20:21 UTC, amir-raissi approved these changes
Think this is good base, need to add/think about the things i described above.

2022-04-12 20:21 UTC, amir-raissi commented on contracts/Vender.sol
> +    (bool sent,) = msg.sender.call{value: address(this).balance}("");
Not sure if this comma will throw error

2022-04-12 21:49 UTC, ahantke1 requested changes

2022-04-12 21:49 UTC, ahantke1 commented on contracts/Vender.sol
> +  function buyTokens() public payable returns (uint256 tokenAmount) {
Not working

2022-04-12 21:49 UTC, ahantke1 commented on contracts/Vender.sol
> +  function buyTokens() public payable returns (uint256 tokenAmount) {
Testing on both hardhat and remix-- tokens are not being received by sender for some reason.

2022-04-12 22:46 UTC, ahantke1 commented on contracts/Vender.sol
> +    (bool sent,) = msg.sender.call{value: address(this).balance}("");
it dont

2022-04-12 22:56 UTC, ahantke1 commented
Fails autotest and manual testing on remix: 

Issue with this line - 
32: uint256 vendorBalance = playToken.balanceOf(address(this));

2022-04-14 17:23 UTC, ahantke1 approved these changes

2022-04-14 17:25 UTC, merged